name: Deploy Hugo site

on:
  push:
    branches: [ "main" ]      # 仅当 main 更新时部署
  workflow_dispatch:          # 手动触发按钮

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache   # 固定缓存目录

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # ① 缓存 Hugo Modules（速度可快 20‑30 s）
      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      # ② 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'   # 或 'latest'
          extended: true

      # ③ 构建
      - name: Build
        run: hugo --gc --minify --baseURL "https://blog.chenatu.cc/"

      # ④ 上传并发布 Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
